"""Every public function, grouped by directory, with its docstring's first sentence.

Fills the gap between the two scans: a linter sees inside one file; duplication
detection only notices copies once they are textually similar, and two
independent implementations of the same idea rarely are. Nothing else reports
the same function written a sixth time under a sixth name.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import PurePosixPath


@dataclass(frozen=True)
class CatalogEntry:
    """One catalogued callable: its name, where it is defined, and the first sentence of its docstring."""

    name: str
    file: str
    line: int
    # First sentence of the docstring, when there is one.
    summary: str | None


_SENTENCE = re.compile(r"^(.*?[.!?])(\s|$)", re.DOTALL)


def _first_sentence(doc: str | None) -> str | None:
    """The first sentence, not the first line: docstrings are written to wrap, so a
    first line alone usually stops mid-clause.
    """
    if not doc:
        return None
    text = " ".join(doc.strip().split())
    if not text:
        return None
    match = _SENTENCE.match(text)
    return (match.group(1) if match else text).strip()


def extract_exports(source: str, file: str) -> list[CatalogEntry]:
    """Pure: given a file's text, the public module-level callables in it.

    A file that does not parse contributes nothing — the catalogue's job is what
    exists to reuse, and a broken file is not that.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    return [
        CatalogEntry(
            name=node.name,
            file=file,
            line=node.lineno,
            summary=_first_sentence(ast.get_docstring(node)),
        )
        for node in tree.body
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and not node.name.startswith("_")
    ]


def _directory_of(file: str) -> str:
    parent = str(PurePosixPath(file).parent)
    return "." if parent == "." else parent


_HEADER = [
    "# Shared helpers",
    "",
    "<!-- Generated by `ebpy catalog`. Regenerate rather than editing. -->",
    "",
    "Read this before writing a helper. The failure it exists to prevent is the same function written",
    "a sixth time under a sixth name, which no linter reports and which duplication detection only",
    "notices once the copies are textually similar — and independently written ones rarely are.",
    "",
]


def render_catalog(entries: list[CatalogEntry]) -> str:
    if not entries:
        return "\n".join([*_HEADER, "No public functions found.", ""])
    directories = sorted({_directory_of(entry.file) for entry in entries})
    sections: list[str] = []
    for directory in directories:
        rows = sorted(
            (entry for entry in entries if _directory_of(entry.file) == directory),
            key=lambda entry: entry.name,
        )
        sections.extend(
            [
                f"## {directory}",
                "",
                "| Helper | Where | What it does |",
                "| --- | --- | --- |",
                *(
                    f"| `{entry.name}` | {entry.file}:{entry.line} | {entry.summary or ''} |"
                    for entry in rows
                ),
                "",
            ]
        )
    return "\n".join([*_HEADER, f"{len(entries)} public functions.", "", *sections])


def catalog_sources(paths: list[str]) -> list[str]:
    return [
        path
        for path in paths
        if path.endswith(".py")
        and "test" not in PurePosixPath(path).name
        and not any(part in {"tests", "test"} for part in PurePosixPath(path).parts)
    ]
